name: build archive

on:
  push:
  # allow manual launch
  workflow_dispatch:

jobs:
  build-archive:
    runs-on: ubuntu-latest
    container: fedora:42
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: dnf install -y git
      # Running inside CI requires PAT secrets for git@github.com: URLs.
      - run: perl -pi -e 's(git\@github.com:)(https://github.com/)' skia-build-clone-since-m70.sh
      - run: ./skia-build-clone-since-m70.sh
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/20')
        with:
          files: |
            skia.git
