name: Main

on:
  push:
    paths-ignore:
      - README.md

jobs:
  build:
    runs-on: ubuntu-latest
    container: fedora:41
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: dnf install -y expat-devel fontconfig-devel freetype-devel harfbuzz-devel brotli-devel
      - run: dnf install -y libicu-devel libjpeg-turbo-devel libwebp-devel libxml2-devel mesa-libGL-devel vulkan-headers
      - run: dnf install -y clang git patch time zip python-unversioned-command ninja-build
      - run: ./download-and-build-skia.sh
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            skia-m*-*

  m87:
    runs-on: ubuntu-latest
    container: fedora:41
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: dnf install -y expat-devel fontconfig-devel freetype-devel harfbuzz-devel brotli-devel
      - run: dnf install -y libicu-devel libjpeg-turbo-devel libwebp-devel libxml2-devel mesa-libGL-devel
      - run: dnf install -y clang git patch time zip python-unversioned-command ninja-build gn
      - run: dnf install -y python3-setuptools python3-pybind11 python3-pytest python3-numpy python3-build python3-devel python3-pillow python3-glfw
      - run: dnf install -y xorg-x11-server-Xvfb python3-pytest-xvfb
      - run: ./download-and-build-skia.sh m87
