name: Main

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    container: fedora:39
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: dnf install -y expat-devel fontconfig-devel freetype-devel harfbuzz-devel brotli-devel
      - run: dnf install -y libicu-devel libjpeg-turbo-devel libwebp-devel libxml2-evel vulkan-headers
      - run: dnf install -y clang++
      - run: ./download-and-build-skia.sh
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            skia-m*-*
